import './globals.css'

import ThemeContextProvider from "../components/ThemeContextProvider"
import ThemeToggleButton from "../components/ThemeToggleButton"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <ThemeToggleButton />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  )
}
